### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by yankeeinlondon** [jonesetc/ember-cli-horizon#1]
![image](https://cloud.githubusercontent.com/assets/980757/15816285/fd841608-2bc9-11e6-8c5d-81f8fb87814f.png)

Installation led to following error; haven't yet looked into this.

**Comment by yankeeinlondon** [comment]
ok, fixed. i knew I'd seen this before. There were a two problems with your generator but I've added a PR which should fix these.

**Comment by jonesetc** [comment]
Fixed by #2
